apiVersion: v1
kind: Secret
metadata:
  name: powerdns-api-key
  labels:
    app: {{ template "pdns.name" . }}
    chart: {{ template "pdns.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  POWERDNS_API_KEY: "{{ .Values.pdns.api.key | b64enc }}"
